x = float(input("First variable: "))
y = float(input("Second variable: "))
print(f"{x} + {y} = {x + y}")
print(f"{x} - {y} = {x - y}")
print(f"{x} * {y} = {x * y}")
print(f"{x} / {y} = {x / y}")
print(f"{x} ** {y} = {x ** y}")
print(f"{x} // {y} = {x // y}")
print(f"{x} % {y} = {x % y}")
print(f"{x} < {y} = {x < y}")
print(f"{x} <= {y} = {x <= y}")
print(f"{x} > {y} = {x > y}")
print(f"{x} >= {y} = {x >= y}")
print(f"{x} == {y} = {x == y}")
print(f"{x} != {y} = {x != y}")
print(f"{x} and {y} = {x and y}")
print(f"{x} or {y} = {x or y}")
print(f"not {x} = {not x}")
print(f"not {y} = {not y}")
print(f"{x} is {y} = {x is y}")
print(f"{x} is not {y} = {x is not y}")

z = float(input("Big number: "))
print(f"{z:,}")  # number with thousands separator
print(f"{z:.2f}")  # number of digits after the decimal point
